Questions part 1 projet
WildCodeSchool/lille-js-202003-project-special-barnacle-frontend pull request #12
Opened 2020-07-17 14:15 UTC by berenice89

2020-07-17 15:29 UTC, YannYves submitted a review, later dismissed
OK to me . We definitely need to create way smaller PR .

2020-07-20 14:00 UTC, LoicBrassart requested changes
- Pourquoi il y a de nouveau des routes pour chaque question, alors que si je me trompe pas on s'était mis d'accord pour qu'il n'y en ait pas (au moins dans un premier temps) ?
- Vu la quantité de code mort, personne (dev ni SM) n'a relu la PR sérieusement avant de me la confier

2020-07-20 14:00 UTC, LoicBrassart commented on src/components/form/Form.jsx
> +// import Question18a from './question/part-1/18a';
Dead code

2020-07-20 14:00 UTC, LoicBrassart commented on src/components/form/Form.jsx
> +    }
Tests should look like this:
```js
    if (answers.question1 === 'Autres projets') {
￼      return <Contact />;
￼    }
```
For this, you should change the `text` key to something like `answers`, and adapt the `useSelector` on line 36

2020-07-20 14:00 UTC, LoicBrassart commented on src/components/form/Stepper.jsx
> +// }
Dead code

2020-07-20 14:00 UTC, LoicBrassart commented on src/index.jsx
> +  // initialState,
Dead code

2020-07-20 16:16 UTC, YannYves approved these changes
ok to me . Hope this works this time

2020-07-20 16:52 UTC, LoicBrassart approved these changes
It seems to fix most of what I asked. The only remaining point (change redux store structure) would require major refactoring, it's not the most important task at hand

2020-07-21 07:24 UTC, merged