Question part 2 financement
WildCodeSchool/lille-js-202003-project-special-barnacle-frontend pull request #13
Opened 2020-07-17 15:01 UTC by berenice89

2020-07-17 15:38 UTC, YannYves approved these changes
OK but way too long

2020-07-20 14:09 UTC, LoicBrassart requested changes
See comments in the review itself

2020-07-20 14:09 UTC, LoicBrassart commented on src/App.jsx
> +          </Route>
There shouldn't have been so many routes.
At the very least, you could have a single `/question/:num` with `:num` being the question's id

2020-07-20 14:09 UTC, LoicBrassart commented on src/App.jsx
> +import Question27b3 from './components/form/question/part-2/27b3';
Does `App` really load all these components ? I thought it was `<Form>`'s job ?

2020-07-20 14:09 UTC, LoicBrassart commented on src/components/form/Form.jsx
> +    question22a: '',
No need for this `useState` if you use Redux and it's `useSelector`

2020-07-20 14:09 UTC, LoicBrassart commented on src/components/form/Form.jsx
> +    case 31:
Shouldnn't this whole `switch(step)` be replaced by `<Form>`'s conditional rendering ?

2020-07-23 11:08 UTC, closed without merging