26 homepage
WildCodeSchool/lille-js-202003-project-special-barnacle-frontend pull request #2
Opened 2020-06-22 09:29 UTC by JulienMartos

2020-06-22 12:19 UTC, YannYves commented on public/index.html
> +    <link
même commentaires que précédemment .

2020-06-22 12:20 UTC, YannYves commented on src/App.css
> +* {
même commentaire que précédemment .

2020-06-22 12:22 UTC, YannYves submitted a review, later dismissed
Ok pour moi . Par contre, les PR doivent être plus petites à l'avenir . 500 lignes max est une bonne pratique . A voir avec Mr Brassart .

2020-06-22 14:32 UTC, LoicBrassart requested changes
SnE

2020-06-22 14:32 UTC, LoicBrassart commented on src/components/styles/header.css
> +}*/
Dead code

2020-06-22 15:40 UTC, YannYves approved these changes
Apparently, No more dead code

2020-06-22 15:40 UTC, YannYves approved these changes
Apparently, No more dead code

2020-06-22 15:42 UTC, YannYves submitted a review, later dismissed
Apparently, No more dead code

2020-06-23 09:22 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-06-23 09:59 UTC, YannYves approved these changes
resolved conflicts

2020-06-29 13:45 UTC, LoicBrassart approved these changes
SnE

2020-06-30 09:05 UTC, merged