241 header boot
WildCodeSchool/lille-js-202003-project-special-barnacle-frontend pull request #3
Opened 2020-06-22 10:08 UTC by JulienMartos

2020-06-22 12:14 UTC, YannYves commented on public/index.html
> +    <link
Ok pour moi, il faudra cependant changer le CDN pour un package NPM .

2020-06-22 12:16 UTC, YannYves commented on src/App.css
> +* {
Pas vraiment fan des selectors du type * ... On peut sûrement avoir quelque chose de plus précis .

2020-06-22 12:18 UTC, YannYves submitted a review, later dismissed
OK pour moi . Des changements mineurs à apporter ;

2020-06-22 14:37 UTC, LoicBrassart requested changes
Oh noes, dead code !

2020-06-22 14:37 UTC, LoicBrassart commented on src/components/styles/header.css
> +.header ul {
Dead code

2020-06-22 14:37 UTC, LoicBrassart commented on src/components/styles/header.css
> +/* COPIER EN STYLEDCOMPONENT DANS HEADER.JSX
Dead code

2020-06-22 15:35 UTC, YannYves submitted a review, later dismissed
No more dead code ! Approved

2020-06-23 09:25 UTC, LoicBrassart submitted a review, later dismissed
No More Evil

2020-06-23 10:08 UTC, YannYves submitted a review, later dismissed
solved conflicts

2020-06-29 13:48 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-06-30 09:48 UTC, YannYves submitted a review, later dismissed
OK , looks alright to me

2020-07-06 08:47 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-07-06 13:28 UTC, YannYves commented
ES lint checks have failed , please review

2020-07-06 13:42 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-07-08 07:26 UTC, YannYves approved these changes
conflict solved

2020-07-08 08:45 UTC, LoicBrassart approved these changes
SnE

2020-07-08 08:47 UTC, merged