18 apropos
WildCodeSchool/lille-js-202003-project-special-barnacle-frontend pull request #5
Opened 2020-06-23 08:55 UTC by berenice89

2020-06-23 09:23 UTC, berenice89 commented
Resolved conflicts in app.jsx

2020-06-23 13:30 UTC, YannYves submitted a review, later dismissed
Looks alright to me !

2020-06-29 13:52 UTC, LoicBrassart requested changes
You should consider *never* commenting code in the first place, to avoid forgetting deleting it later

2020-06-29 13:52 UTC, LoicBrassart commented on src/components/BurgerMenu.jsx
> +  left: 2rem; */
Dead code

2020-06-29 13:52 UTC, LoicBrassart commented on src/components/BurgerMenu.jsx
> +    /*position: relative;*/
Dead code

2020-06-29 15:31 UTC, YannYves submitted a review, later dismissed
Dead code removed

2020-06-30 09:45 UTC, YannYves commented
ESLint check failed . Please review .

2020-06-30 09:46 UTC, YannYves requested changes
ESLint Check failed, please review .

2020-07-03 07:40 UTC, YannYves submitted a review, later dismissed
ok

2020-07-06 08:49 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-07-06 13:10 UTC, YannYves approved these changes
ok to me

2020-07-06 13:44 UTC, LoicBrassart approved these changes
SnE

2020-07-07 09:26 UTC, merged